import "./globals.css";
import { Instrument_Sans } from "next/font/google";
import LayoutClient from "./LayoutClient";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Cheaphualing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={instrumentSans.className}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
